name: Container Security Scan

on:

  repository_dispatch:
    types: [container-security-scan]

jobs:
  container-security-scan:
    runs-on: ubuntu-latest
    name: Container Security Scan with Trivy
    
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull the latest image
        # Usa el tag del payload
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/lab5:latest || true

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.67.2
      
      - name: Run Trivy vulnerability scanner
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          # Usa el tag del payload
          image-ref: ${{ secrets.DOCKER_USERNAME }}/lab5:latest
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'
          exit-code: 1 # Si Trivy encuentra HIGH/CRITICAL, falla el paso inmediatamente
          ignore-unfixed: false
          skip-setup-trivy: true

      - name: Upload Trivy scan results to GitHub Security tab
        # Se ejecuta incluso si el paso anterior falló (para subir los resultados)
        if: always() 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'container-scan'

      - name: Disparar el flujo de Despliegue (a Azure)
        # Esto solo se ejecuta si el escaneo de Trivy (paso 7) fue exitoso
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Dispara el flujo de Azure Container App, enviando la imagen escaneada
          event-type: deploy_azure_container
          client-payload: '{"status": "success", "scan_results": "No se encontraron vulnerabilidades críticas o altas", "sha": "${{ github.event.client_payload.sha }}", "run_number": "${{ github.event.client_payload.run_number }}"}'